export {default as Home} from "./Home"
export {default as Login} from "./Login"
export {default as Register} from "./Register"
export {default as Pagenotfound} from "./Pagenotfound"
export {default as About} from "./About"
// export {default as addmin} from "./addmin/DashBord"
